import type { DayProfileSettings } from "./profile-types";

export const DEFAULT_DAY_PROFILE_SETTINGS: DayProfileSettings = {
	enabled: true,
	packs: [
		{
			id: "pack:governance",
			label: "Governance baseline",
			recipes: [
				{
					id: "r0-morning",
					label: "R0 (early)",
					window: { start: "09:00", end: "10:00" },
					kind: "governance:r0",
					profile: { mode: "admin" },
					chunkMinutes: 35,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 1,
					priority: 10,
				},
				{
					id: "b5-commit-midday",
					label: "B5 commit (if needed)",
					window: { start: "12:00", end: "13:30" },
					kind: "governance:b5-commit",
					profile: { mode: "admin" },
					chunkMinutes: 15,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 6,
					priority: 20,
				},
			],
		},
		{
			id: "pack:weekday-core",
			label: "Weekday core",
			recipes: [
				{
					id: "wk-morning-deep",
					label: "Execute (deep morning)",
					window: { start: "10:00", end: "12:00" },
					kind: "op:b5-execute",
					profile: { mode: "deep" },
					chunkMinutes: 90,
					allowAuthority: false,
					minUrgency: "medium",
					priority: 100,
				},
				{
					id: "wk-early-afternoon-shallow",
					label: "Execute (shallow)",
					window: { start: "14:00", end: "17:30" },
					kind: "op:b5-execute",
					profile: { mode: "shallow" },
					chunkMinutes: 45,
					allowAuthority: false,
					minUrgency: "medium",
					priority: 200,
				},
				{
					id: "wk-late-workshop",
					label: "Workshop (pipeline health)",
					window: { start: "17:30", end: "19:00" },
					kind: "op:b4-workshop",
					profile: { mode: "admin" },
					chunkMinutes: 30,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 8,
					priority: 210,
				},
				{
					id: "wk-evening-close",
					label: "Close (authority)",
					window: { start: "19:00", end: "19:45" },
					kind: "op:b3-close",
					profile: { mode: "admin" },
					chunkMinutes: 20,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 6,
					priority: 220,
				},
				{
					id: "wk-evening-judge",
					label: "Judge (triage / review)",
					window: { start: "19:45", end: "20:30" },
					kind: "op:b2-judge",
					profile: { mode: "admin" },
					chunkMinutes: 30,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 10,
					priority: 230,
				},
				{
					id: "wk-tail-embargo",
					label: "Embargo / unwind",
					window: { start: "20:30", end: "21:30" },
					kind: "op:b6-embargo",
					profile: { mode: "shallow" },
					chunkMinutes: 30,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 6,
					priority: 900,
				},
			],
		},
		{
			id: "pack:weekend-family",
			label: "Weekend lighter",
			recipes: [
				{
					id: "we-late-r0",
					label: "R0 (late morning)",
					window: { start: "10:30", end: "12:00" },
					kind: "governance:r0",
					profile: { mode: "admin" },
					chunkMinutes: 35,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 1,
					priority: 10,
				},
				{
					id: "we-afternoon-exec",
					label: "Execute (shallow)",
					window: { start: "15:00", end: "17:00" },
					kind: "op:b5-execute",
					profile: { mode: "shallow" },
					chunkMinutes: 45,
					allowAuthority: false,
					minUrgency: "low",
					priority: 200,
				},
				{
					id: "we-evening-workshop",
					label: "Workshop (light)",
					window: { start: "17:00", end: "18:00" },
					kind: "op:b4-workshop",
					profile: { mode: "admin" },
					chunkMinutes: 30,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 6,
					priority: 300,
				},
				{
					id: "we-tail-embargo",
					label: "Embargo / unwind",
					window: { start: "20:00", end: "21:00" },
					kind: "op:b6-embargo",
					profile: { mode: "shallow" },
					chunkMinutes: 30,
					allowAuthority: true,
					minUrgency: "low",
					maxTasks: 6,
					priority: 900,
				},
			],
		},
	],
	grandProfiles: [
		{
			id: "profile:weekday-default",
			label: "Weekday default",
			priority: 100,
			selectors: [{ kind: "weekday" }],
			packIds: ["pack:governance", "pack:weekday-core"],
			schedule: {
				// life horizon defaults
				workHours: { start: "09:00", end: "23:00" }, // we can rename later to dayHours; keep for now
				lunch: { start: "12:30", minutes: 45 },
			},
		},
		{
			id: "profile:weekend-default",
			label: "Weekend default",
			priority: 110,
			selectors: [{ kind: "weekend" }],
			packIds: ["pack:weekend-family"],
			schedule: {
				workHours: { start: "10:00", end: "23:30" },
				lunch: { start: "13:00", minutes: 60 },
			},
		},
	],
};
